# Generated by Django 6.0.6 on 2026-06-04 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('products', '0001_initial'),
        ('receipts', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('product_context', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('auto_paused', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_campaigns', to='brands.brand')),
                ('products', models.ManyToManyField(related_name='review_campaigns', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('held', 'Held'), ('removed', 'Removed')], max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('review_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='reviews.reviewcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewModeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_published', models.BooleanField(default=False)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('removal_reason', models.CharField(blank=True, max_length=255)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_reviews', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='reviews.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('ai', 'AI-generated'), ('custom', 'Brand custom')], default='ai', max_length=10)),
                ('review_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='reviews.reviewcampaign')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('messages', models.JSONField(blank=True, default=list)),
                ('hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_session', to='wallets.hold')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_sessions', to='products.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='receipts.receipt')),
                ('review_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='reviews.reviewcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='reviews.reviewsession'),
        ),
        migrations.AddIndex(
            model_name='reviewcampaign',
            index=models.Index(fields=['brand', 'status'], name='reviews_rev_brand_i_69602d_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewsession',
            index=models.Index(fields=['user', 'status'], name='reviews_rev_user_id_a9d01c_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewsession',
            index=models.Index(fields=['review_campaign', 'status'], name='reviews_rev_review__4540ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewsession',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'receipt'), name='uniq_review_session_per_receipt_product'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'status'], name='reviews_rev_product_0aaa55_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'product'], name='reviews_rev_user_id_eefe96_idx'),
        ),
    ]
