# Generated by Django 6.0.6 on 2026-06-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
