# Generated by Django 6.0.6 on 2026-06-04 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('receipts', '0001_initial'),
        ('reservations', '0002_alter_reservation_status'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('issued', 'Issued')], default='issued', max_length=10)),
                ('issued_at', models.DateTimeField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='brands.brand')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='campaigns.campaign')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='receipts.receipt')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='redemption', to='reservations.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardIssuance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('brand_fee_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallets.ledgerentry')),
                ('brand_reward_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallets.ledgerentry')),
                ('customer_credit_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallets.ledgerentry')),
                ('hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallets.hold')),
                ('redemption', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issuance', to='rebates.redemption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['brand', '-created_at'], name='rebates_red_brand_i_4f5a62_idx'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['user', '-created_at'], name='rebates_red_user_id_864b8f_idx'),
        ),
    ]
