# Generated by Django 6.0.6 on 2026-06-04 05:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('scale', 'Scale')], unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rebate_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('review_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_access_level', models.CharField(choices=[('anonymized', 'Anonymized'), ('full', 'Full')], default='anonymized', max_length=20)),
                ('customer_data_module', models.BooleanField(default=False, help_text='Whether the brand can access the Customers module.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
    ]
