# Generated by Django 6.0.6 on 2026-06-04 06:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('next_charge_at', models.DateTimeField(db_index=True)),
                ('last_charged_at', models.DateTimeField(blank=True, null=True)),
                ('total_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='brands.brand')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
