# Generated by Django 6.0.6 on 2026-07-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_avatar_url_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('brand', 'Brand member'), ('admin', 'Platform admin')], default='consumer', max_length=20),
        ),
    ]
