# Generated by Django 6.0.6 on 2026-06-05 02:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('brands_total', models.PositiveIntegerField(default=0)),
                ('active_brands', models.PositiveIntegerField(default=0)),
                ('users_total', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('reservations_total', models.PositiveIntegerField(default=0)),
                ('redemptions_total', models.PositiveIntegerField(default=0)),
                ('reviews_total', models.PositiveIntegerField(default=0)),
                ('total_reward_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservations', models.PositiveIntegerField(default=0)),
                ('active_reservations', models.PositiveIntegerField(default=0)),
                ('approvals', models.PositiveIntegerField(default=0)),
                ('rejected_receipts', models.PositiveIntegerField(default=0)),
                ('redemptions', models.PositiveIntegerField(default=0)),
                ('reward_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fee_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_stats', to='brands.brand')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-total_spend'],
            },
        ),
        migrations.CreateModel(
            name='ProductStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redemptions', models.PositiveIntegerField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reward_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stats', to='brands.brand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='products.product')),
            ],
            options={
                'ordering': ['-redemptions'],
            },
        ),
    ]
