# Generated by Django 6.0.6 on 2026-06-04 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('products', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('merchant', models.CharField(blank=True, max_length=255)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('matched', models.BooleanField(default=False)),
                ('matched_units', models.PositiveIntegerField(default=0)),
                ('decision_reason', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='brands.brand')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='campaigns.campaign')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='reservations.reservation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='mock', max_length=50)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='receipts.receipt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManualReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_queue', to='brands.brand')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_review_items', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_item', to='receipts.receipt')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('duplicate', 'Duplicate receipt'), ('no_match', 'Product not matched'), ('velocity', 'Too many active claims'), ('manual', 'Manually flagged')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_fraud_flags', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='receipts.receipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('normalized', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_line_items', to='products.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='receipts.receipt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['brand', 'status'], name='receipts_re_brand_i_0028d0_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'status'], name='receipts_re_user_id_12510a_idx'),
        ),
        migrations.AddIndex(
            model_name='manualreviewitem',
            index=models.Index(fields=['brand', 'status'], name='receipts_ma_brand_i_f01250_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['user', 'resolved'], name='receipts_fr_user_id_ae2e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['brand', 'resolved'], name='receipts_fr_brand_i_c7cdb5_idx'),
        ),
    ]
